### ISSUE TITLE
运行npm run Dev element-ui vue-resource element-ui/lib/theme-default/index.css找不到

### ISSUE THREAD

**Issue by 547377507** [deshes/vue-weather#1]
运行npm run Dev 
element-ui 、
vue-resource、
element-ui/lib/theme-default/index.css
找不到

**Comment by allanwxl** [comment]
你用的element-ui是2.0版本吧   2.0版本的样式文件变更了

**Comment by deshes** [comment]
import 'element-ui/lib/theme-chalk/index.css';
